default_platform(:android)
platform :android do
  desc "Submit a new build to alpha Track on Play"
  lane :alpha do
    gradle(
      gradle_path: "/usr/bin/gradle",
      task: "bundle",
      build_type: "Release"
    )
    gradle(
      gradle_path: "/usr/bin/gradle",
      task: "assemble",
      build_type: "Release"
    )
    upload_to_play_store(
        version_code: ENV['GITHUB_RUN_NUMBER'],
        track: 'internal',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        release_status: "draft",
      )
  end
end